### ISSUE TITLE
Some dates missing from BSE data

### ISSUE THREAD

**Issue by Rahib4** [hemenkapadia/getbhavcopy#5] opened 2017-06-04 11:52 UTC
Hi Hemen,

Loads of thanks to you for your awesome work, recently I saw that some of the days are missing from BSE data. I checked the log file, I see an error message saying "Error	Could not find file BSEbhav.gbc" in the temp folder. Attaching the log file for your reference. 

Please let me know if you need any help from my side in order to debug this issue.
you can also mail me @saiyad.srh007@gmail.com

Regards,
Saiyad Rasikh

[log.txt](https://github.com/hemenkapadia/getbhavcopy/files/1050278/log.txt)

**Comment by hemenkapadia** [comment] 2018-02-25 00:26
Not sure what the issue is. While working on version 2.1.11a did not experience any other issue. 
Closing this as wont fix. If needed reopen the bug with more details about the issue

**Closed by hemenkapadia** 2018-02-25 00:26 UTC
Labels: bug, investigate, wontfix
