### ISSUE TITLE
v3.0.1a error (log image attached)

### ISSUE THREAD

**Issue by shahss71** [hemenkapadia/getbhavcopy#126] opened 2020-01-04 04:33 UTC
![bhav](https://user-images.githubusercontent.com/59327728/71759836-67a6ff80-2ed9-11ea-9389-d736cbdc3917.PNG)

www.nseindia.com is new site , old site shifted to www1.nseindia.com
v3.0.1a not accessing zip files please help

![bhav2](https://user-images.githubusercontent.com/59327728/71759929-5b23a680-2edb-11ea-83c3-503d9448f407.PNG)

Today it started downloading index data but bhacopy (zip) file error

![BHAV3](https://user-images.githubusercontent.com/59327728/71776417-5b916f80-2fb7-11ea-95e2-3023a5a0f89b.PNG)

**Comment by chaudharidipesh** [comment] 2020-01-04 05:40
I also get the same error.

**Comment by neilazavedo** [comment] 2020-01-04 12:57
The zip file created in the temp folder i.e NSEZip.zip cannot be extracted ... that's the issue ..

**Comment by dsmgecj** [comment] 2020-01-05 17:45
SAME PROBLEM I AM FACING

**Comment by hemenkapadia** [comment] 2020-01-07 06:54
Closing duplicate of #127 and #130

**Closed** 2020-01-07 06:54 UTC
Labels: duplicate
