### ISSUE TITLE
Unable to download bhavcopy from BSE

### ISSUE THREAD

**Issue by dattaninilesh** [hemenkapadia/getbhavcopy#72] opened 2019-01-28 15:40 UTC
Respected Hemen,

I got a message to download latest version of getbhavcopy. I downloaded new version from your website however, I am still getting the same message and unable to download bhavcopy. I have attached the screenshot. Please help.

![error](https://user-images.githubusercontent.com/45917080/51847163-201b0980-2341-11e9-8b71-097fcbf3925a.JPG)

**Comment by hemenkapadia** [comment] 2019-01-28 16:46
Closing as duplicate of #68 - we will keep the discussion in the single thread.

**Closed by hemenkapadia** 2019-01-28 16:46 UTC
Labels: BSE, Indices, bug, duplicate
