### ISSUE TITLE
Getbhavcopy not working any solution?

### ISSUE THREAD

**Issue by dipvarsha1234** [hemenkapadia/getbhavcopy#129] opened 2020-01-04 10:45 UTC
Getbhavcopy not working any solution?

**Comment by neilazavedo** [comment] 2020-01-04 12:31
Please refer to https://github.com/hemenkapadia/getbhavcopy/issues/125 for a possible solution ..

**Comment by neilazavedo** [comment] 2020-01-04 12:55
Yes there is an issue or the NSEZip.zip file created in the temp folder

**Comment by kaly422000593** [comment] 2020-01-04 18:30
new nse site is launched so all downloaders need to update to match url

**Comment by neilazavedo** [comment] 2020-01-05 09:16
![getbhav301a-20200105](https://user-images.githubusercontent.com/58835329/71777734-11fe5000-2fca-11ea-9c1a-fb840d527c13.jpg)
![getbhav301a-20200105b](https://user-images.githubusercontent.com/58835329/71777735-1aef2180-2fca-11ea-8a1d-a8cc502d3d0a.jpg)
[log.txt](https://github.com/hemenkapadia/getbhavcopy/files/4023049/log.txt)

**Comment by arvindeept** [comment] 2020-01-06 05:22
Not working.

**Comment by kaly4200149** [comment] 2020-01-06 07:48
sir pls if u can change the url of nse site.   the old site is www1.nseindia.com  or new site have different url of bhavcopy and indices etc and also for donation use debit card or net baning link

**Comment by bijoy2526** [comment] 2020-01-06 10:50
after some days old site may be closed and new site it seems eod data is also paid service.

**Comment by bijoy2526** [comment] 2020-01-06 16:39
no data of today?

**Comment by neilazavedo** [comment] 2020-01-06 16:41
Data is updated here : https://github.com/hemenkapadia/getbhavcopy/issues/127

**Comment by hemenkapadia** [comment] 2020-01-07 06:50
Closing - duplicate of #127

**Closed by hemenkapadia** 2020-01-07 06:50 UTC
