### ISSUE TITLE
Unable to install bhavcopy 

### ISSUE THREAD

**Issue by Binay22Singh** [hemenkapadia/getbhavcopy#57] opened 2019-01-23 05:47 UTC
Sir download the file but its not working its says Getbhavcopy has stop working pl;z help
Problem signature:
Problem Event Name:	CLR20r3
Problem Signature 01:	getbhavcopy.exe
Problem Signature 02:	2.1.12.39573
Problem Signature 03:	5c46b130
Problem Signature 04:	System
Problem Signature 05:	4.0.0.0
Problem Signature 06:	4ba1dff4
Problem Signature 07:	1d21
Problem Signature 08:	18
Problem Signature 09:	System.NotSupportedException
OS Version:	6.1.7600.2.0.0.256.1
Locale ID:	2057
Additional Information 1:	abec
Additional Information 2:	abecbc5f63be1ef86b00eed0c5362fc8
Additional Information 3:	2825
Additional Information 4:	282522ac5f34aed6b6d919fa901d70ac

Read our privacy statement online:
http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
C:\Windows\system32\en-US\erofflps.txt

**Comment by hemenkapadia** [comment] 2019-01-23 08:22
Closed duplicate of #58 . Will use that issue for investigating a solution.

**Closed by hemenkapadia** 2019-01-23 08:22 UTC
Labels: duplicate

**Comment by Binay22Singh** [comment] 2019-01-23 08:37
request you to kindly issue new version
