### ISSUE TITLE
ERROR bse server did not return data

### ISSUE THREAD

**Issue by SANEVK** [hemenkapadia/getbhavcopy#46] opened 2018-12-19 19:39 UTC
HEMEN sir,
   for last few days we are getting error in downloading BSE EOD DATA
please look into the matter & help.
thanks in advance

**Comment by Krunal134** [comment] 2019-01-05 06:08
getting Error For All BSE

Error	Error getting VIEWSTATE information for Index Data HTTP POST for GREENEX
Error	The remote server returned an error: (301) Moved Permanently Redirect.

**Comment by hemenkapadia** [comment] 2019-01-06 03:54
Hi @SANEVK  and @Krunal134 , Thanks for bringing this to my notice. I have started investigating this.

**Comment by SANEVK** [comment] 2019-01-06 05:13
Sir,

       It’s a part of  my duty as a team member.

Problem persists for NSE & BSE .

Sure to hear a positive solution from you soon.

Thanks in advance.

----- Mr. SANE V. K.

------- CONTACT NO. 9423002781

**Comment by SANEVK** [comment] 2019-01-07 18:33
Sir,

     Could you succeed to fix bug in 2.1.11a version FOR BSE & NSE ?

Please inform us as soon as you complete.

Hope to hear from you soon.

----- Mr. SANE V. K.

----- CONTAACT NO. 9423002781

**Comment by hemenkapadia** [comment] 2019-01-09 04:00
Investigated the root cause. This issue occurs because BSE has changed the way it provides indices data. The old endpoints no longer work. Will need to modify Getbhavcopy to support the new Endpoints.

**Comment by SANEVK** [comment] 2019-01-12 07:52
Sir,

   This is an humble reminder.

      Hope  you will be able to fix up bug in getbhavcopy  & we will get modified version in couple of days time.

 

Just for your reference that we are facing this problem from 15th dec’2018.

 

Thanks in advance.

------Mr. SANE V. K.

---- CONTACT NO. 9423002781

**Comment by hemenkapadia** [comment] 2019-01-14 08:09
This is fixed, i still need to work on other issues that are tagged to the next 2.1.12a release. I am trying my best to get some time from my work schedule to get the next version out. Should be completed this week.

**Comment by SANEVK** [comment] 2019-01-14 08:20
SIR,

  Thanks for finding time & fixing bugs.

Are we supposed to download 2.1.11a release again from git hub site to start downloading daily data or we should wait for your next 2.1.12a release?

Please advise.

Thanks in advance.

---- Mr. SANE V. K.

------ CONTACT NO. 9423002781

N. B.:- IS THIS DATA IN CSV FORMAT?

**Comment by hemenkapadia** [comment] 2019-01-14 08:44
You need to wait till i release the next version.

**Comment by hemenkapadia** [comment] 2019-01-14 08:47
Fixed. Closing this issue as fix development is completed. Waiting for the next release to complete development work on the other bugs slated in the 2.1.12a release.

**Closed by hemenkapadia** 2019-01-14 08:47 UTC
Labels: BSE, enhancement, to be investigated

**Comment by SANEVK** [comment] 2019-01-14 09:46
SIR,

   Thanks for a prompt reply.

Just one doubt.

Whether we will be able to download bse/nse data from 15th December 2018 onwards ( because problem started from that date.) ??

OR you suggest any other solution for the lapse period?

--------  Mr. SANE V. K.

**Comment by hemenkapadia** [comment] 2019-01-15 18:45
You will be able to download back dated data...
