### ISSUE TITLE
Error In Getbhavcopy V2.1.11a

### ISSUE THREAD

**Issue by Krunal134** [hemenkapadia/getbhavcopy#29] opened 2018-03-19 07:11 UTC
Message	*********  Starting Getbhavcopy  *********
Message	Error checking version support for Getbhavcopy using Github API.
Message	The request was aborted: Could not create SSL/TLS secure channel.
Message	Checking with Raw Github content
Message	Error checking version support for Getbhavcopy using Raw Github content.
Message	The remote server returned an error: (403) Forbidden.

Kindly FIX It !!!!

**Comment by Krunal134** [comment] 2018-07-21 13:15
I use win8 ... But it works fine now ...

Only issue is that I am not getting data of NSE SMALLCAP 100 & NSE MIDCAP 100

Pls fix it !!!

**Comment by Prashis44** [comment] 2018-07-22 11:37
hi
i am getting the same error , windows 7, 32 bit

**Comment by raoge** [comment] 2019-01-04 13:48
Sir, I am using Windows 10. I am still getting the error;
Message	*********  Starting Getbhavcopy  *********
Message	Error checking version support for Getbhavcopy using Github API.
Message	The request was aborted: Could not create SSL/TLS secure channel.
Message	Checking with Raw Github content

Message	Downloading BSE Equity Bhavcopy
Error	Error getting VIEWSTATE information for Index Data HTTP POST for SENSEX

I can view http://www.getbhavcopy.com/release.txt page as 
{
  "tag_name": "2.1.11a",
  "name": "Getbhavcopy version 2.1.11a"
}.

Please fix the same..
thanks.

**Comment by Krunal134** [comment] 2019-01-05 06:10
Error @hemenkapadia 
Error	Error getting VIEWSTATE information for Index Data HTTP POST for GREENEX
Error	The remote server returned an error: (301) Moved Permanently Redirect.

**Comment by hemenkapadia** [comment] 2019-01-06 04:01
Hi,

This this a known error. Please check
https://github.com/hemenkapadia/getbhavcopy/issues/46 for further updates
on the issue. I have started looking into this issue

Regards,
Hemen

**Comment by hemenkapadia** [comment] 2019-01-17 05:58
Since the original issue was about HTTPS error communicating with Github API, using this issue to track the fix implemented to get TLS 1.2 working on .NET framework 4.0
https://stackoverflow.com/questions/33761919/tls-1-2-in-net-framework-4-0

Implemented the changes as suggested in version 2.1.12a and confirmed that https on the github api now works.

**Comment by hemenkapadia** [comment] 2019-01-17 06:11
Closed as fixed in code. Waiting for release

**Closed by hemenkapadia** 2019-01-17 06:11 UTC
Labels: to be investigated

**Comment by tusharmdave** [comment] 2020-01-06 14:26
01/06/2020 19:55:56	Message	*********  Downloading Data for 06-01-2020  *********
01/06/2020 19:55:57	Message	Downloading NSE Equity Bhavcopy
01/06/2020 19:55:58	Error	Could not extract NSE zip file.
01/06/2020 19:55:58	Error	Cannot find central directory
01/06/2020 19:55:59	Message	Downloading index data for NSENIFTY
