### ISSUE TITLE
Application fails to download NSE data

### ISSUE THREAD

**Issue by SubashDump** [hemenkapadia/getbhavcopy#3] opened 2017-04-26 10:15 UTC
The application is failing to download the NSE data, below is the log.
04/26/2017 15:22:46	Message	*********  Starting Getbhavcopy  *********
04/26/2017 15:28:51	Message	Settings Saved
04/26/2017 15:29:17	Message	Downloading symbols for index NSENIFTY
04/26/2017 15:29:17	Message	Downloading symbols for index NIFTYJUNIOR
04/26/2017 15:29:17	Message	Downloading symbols for index NSE100
04/26/2017 15:29:17	Error	Error downloading symbols for index NSE100 from https://www.nseindia.com/content/indices/ind_cnx100list.csv
04/26/2017 15:29:17	Error	The remote server returned an error: (404) Not Found.
04/26/2017 15:29:18	Message	Downloading symbols for index NSE500
04/26/2017 15:29:18	Error	Error downloading symbols for index NSE500 from https://www.nseindia.com/content/indices/ind_cnx500list.csv
04/26/2017 15:29:18	Error	The remote server returned an error: (404) Not Found.
04/26/2017 15:29:18	Message	Downloading symbols for index MIDCAP50
04/26/2017 15:29:18	Message	Downloading symbols for index NSEMIDCAP
04/26/2017 15:29:18	Error	Error downloading symbols for index NSEMIDCAP from https://www.nseindia.com/content/indices/ind_cnxmidcaplist.csv
04/26/2017 15:29:18	Error	The remote server returned an error: (404) Not Found.
04/26/2017 15:29:18	Message	Downloading symbols for index BANKNIFTY
04/26/2017 15:29:18	Error	Error downloading symbols for index BANKNIFTY from https://www.nseindia.com/content/indices/ind_cnxbanklist.csv
04/26/2017 15:29:18	Error	The remote server returned an error: (404) Not Found.
04/26/2017 15:29:18	Message	Downloading symbols for index NSEIT
04/26/2017 15:29:23	Error	Error downloading symbols for index NSEIT from https://www.nseindia.com/content/indices/ind_cnxitlist.csv
04/26/2017 15:29:23	Error	The remote server returned an error: (404) Not Found.

I am latest (downloaded  today 25-April-2017) version.
Let me know if you need more information

Thanks
Subash

**Comment by hemenkapadia** [comment] 2017-06-08 05:00
Hi @SubashDump ,

Are you still facing this issue ? Occasionally such issues seem to appear but then they auto resolve itself as the issue is usually with NSE server.

Regards,
Hemen

**Comment by SubashDump** [comment] 2017-06-08 06:40
Hi Hemen ,

 

It is consistent , I tried couple of times across different timing , days .

Let me know if need more information like logs, screenshots etc. 

Thanks

Subash

**Comment by hemenkapadia** [comment] 2018-02-25 00:29
While working on version 2.1.11a I did not notice any such issue. Maybe a temp glicth on the NSE server to return 404 error messages.
Closing bug, wontfix since working as expected

**Closed by hemenkapadia** 2018-02-25 00:29 UTC
Labels: bug, invalid, investigate
