### ISSUE TITLE
getbhavopy is not working

### ISSUE THREAD

**Issue by madhumailbox** [hemenkapadia/getbhavcopy#124] opened 2020-01-02 03:09 UTC
same issue of 3.0.0 persists now also 

Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for NIFTYMEDIA
Error	Error downloading Index Data for NIFTYMEDIA
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for NIFTYMETAL
Error	Error downloading Index Data for NIFTYMETAL
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for NIFTYPHARMA
Error	Error downloading Index Data for NIFTYPHARMA
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for NIFTYPVTBANK
Error	Error d

**Comment by hemenkapadia** [comment] 2020-01-02 08:15
Closed. Duplicate of issue #125

**Closed by hemenkapadia** 2020-01-02 08:15 UTC
