### ISSUE TITLE
 Error	Error downloading Index Data for NSENIFTY

### ISSUE THREAD

**Issue by sanku74** [hemenkapadia/getbhavcopy#131] opened 2020-01-06 14:38 UTC
Error	Error downloading Index Data for NSENIFTY
Error	The underlying connection was closed: The connection was closed unexpectedly.
Message	Downloading index data for NIFTYJUNIOR
Error	Error downloading Index Data for NIFTYJUNIOR
Error	The underlying connection was closed: The connection was closed unexpectedly.
Message	Downloading index data for NIFTYMIDCAPLIQ15

**Comment by sanku74** [comment] 2020-01-06 14:39
Please help me as I am not able to download through Getbhvcopy

**Comment by neilazavedo** [comment] 2020-01-06 16:13
Data is uploaded here : https://github.com/hemenkapadia/getbhavcopy/issues/127

**Comment by hemenkapadia** [comment] 2020-01-07 06:51
Closed - duplicate of #127

**Closed by hemenkapadia** 2020-01-07 06:51 UTC
Labels: duplicate
