### ISSUE TITLE
02/04/2018 to till date Error	NSEMIDCAP , NIFTYSMALL100 Error	NSE server did not return data for index NIFTYSMALL100

### ISSUE THREAD

**Issue by devismodi** [hemenkapadia/getbhavcopy#32] opened 2018-04-10 09:13 UTC
Message	Error checking version support for Getbhavcopy using Github API.
Message	The underlying connection was closed: An unexpected error occurred on a send.
Message	Checking with Raw Github content
Message	*********  Downloading Data for 02-04-2018  *********
Message	Downloading NSE Equity Bhavcopy
Message	Downloading index data for NSENIFTY
Message	Downloading index data for NIFTYJUNIOR
Message	Downloading index data for NIFTYLIQ15
Message	Downloading index data for NIFTYMIDCAPLIQ15
Message	Downloading index data for NSE100
Message	Downloading index data for NIFTY200
Message	Downloading index data for NSE500
Message	Downloading index data for MIDCAP50
Message	Downloading index data for NSEMIDCAP
Error	NSE server did not return data for index NSEMIDCAP
Message	Downloading index data for NIFTYSMALL100
Error	NSE server did not return data for index NIFTYSMALL100
Message	Downloading index data for NIFTYAUTO
Message	Downloading index data for BANKNIFTY
Message	Downloading index data for NIFTYENERGY
Message	Downloading index data for NIFTYFINSERVICE

**Comment by devismodi** [comment] 2018-04-23 16:10
Error NSE server did not return data for index NSEMIDCAP
Error NSE server did not return data for index NIFTYSMALL100

**Comment by hemenkapadia** [comment] 2018-07-19 06:17
Closed, duplicate of #33

**Closed by hemenkapadia** 2018-07-19 06:17 UTC
Labels: duplicate
