### ISSUE TITLE
Does not open at all

### ISSUE THREAD

**Issue by vinish12345** [hemenkapadia/getbhavcopy#89] opened 2019-06-28 13:34 UTC
sir

getbhavcopy doesnot open at all. i redownloaded but still the problem persists.  I use windows 10.

**Comment by BoyMumbai** [comment] 2019-07-05 15:15
Same Issue I also faced

It stopped working after installing the new update .Net

**Comment by hemenkapadia** [comment] 2019-09-14 15:27
Possible duplicate of #90. Can you please share more details on #90? I am marking this one as closed -dupliate

**Closed by hemenkapadia** 2019-09-14 15:27 UTC
