### ISSUE TITLE
Even after donating the amount, bhavcopy software is not working..any clue?

### ISSUE THREAD

**Issue by satyamgargg** [hemenkapadia/getbhavcopy#91] opened 2019-07-07 07:07 UTC

**Comment by hemenkapadia** [comment] 2019-09-05 06:01
This has nothing to do with Donations. I never disable any functionality in Getbhavcopy with the intent of collecting money. The donation link is purely provided for those who want to contribute voluntarily.

**Comment by hemenkapadia** [comment] 2019-09-14 15:31
possible duplicate of #95.

@satyamgargg, are you still having issues? Marking this as closed duplicate. We will discuss more about this in issue #95.

**Closed by hemenkapadia** 2019-09-14 15:31 UTC
Labels: duplicate
