### ISSUE TITLE
Get Bhav Copy Not Opening after New .Net update 

### ISSUE THREAD

**Issue by BoyMumbai** [hemenkapadia/getbhavcopy#90] opened 2019-07-05 15:17 UTC
Get Bhav Copy Not Opening after installing New .Net update received from Microsoft

**Comment by hemenkapadia** [comment] 2019-09-14 15:26
Can you share more details? I checked on my machine Windows 10, with all latest updates turned on and it seems to work just fine.

**Comment by hemenkapadia** [comment] 2019-09-14 15:32
Possible duplicate of #95. Closing as duplicate. @BoyMumbai, if you are still having issues please share the details on #95.

**Closed by hemenkapadia** 2019-09-14 15:32 UTC
Labels: duplicate
