### ISSUE TITLE
getbhavcopy v. 3.0.1a giving following error while downloading nse equity and FnO bhavecopy

### ISSUE THREAD

**Issue by bpgandhi** [hemenkapadia/getbhavcopy#135] opened 2020-01-07 07:13 UTC
![image](https://user-images.githubusercontent.com/58802244/71875806-32094d00-314b-11ea-9390-4e3f17aabd1b.png)

![image](https://user-images.githubusercontent.com/58802244/71875815-3afa1e80-314b-11ea-9f61-609d5f6ef9b0.png)

**Comment by hemenkapadia** [comment] 2020-01-07 07:53
closed duplicate of #127

**Closed by hemenkapadia** 2020-01-07 07:53 UTC
Labels: duplicate
